[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
df_pairs = "empty_pictures.empty_pictures:empty_pictures"
df_split = "train_val_split.train_val_split:train_val_split"
df_4parts = "big_image_to4parts.big_image_to4parts:big_image_to4parts"
df_hash_db = "dataset_fingerprint.fingerprint_creator:fingerprint_creator"
df_decimator = "simalar_images_finder.similarity_test:similarity_test"
df_hash_xf = "db_folder_intersection.db_folder_intersection:intersector"

[project]
name = "data-managment-toolbox"
version = "0.0.4"
authors = [
  { name="ioretcio", email="goncharukyou@example.com" },
]
description = "a knife for data"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]